/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.onlineshopmanager;

import java.io.File;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Akmal Nizam
 */
public class Sign_Up extends javax.swing.JFrame {
    
    File f = new File("C:\\Users\\Akmal Nizam\\Desktop\\CSC232 Final Project\\UserData");
    String Username, Password, Confirm_Password, Email;
    int ln;
    /**
     * Creates new form Home
     */
    public Sign_Up() {
        initComponents();
    }
    
    void createFolder(){
        if(!f.exists()){
            f.mkdirs();
        }
    }
    
    void readFile(){
        try{
        FileReader fr = new FileReader(f+"\\logins.txt");
        System.out.println("file exits!");
        }
        catch(FileNotFoundException ex){
            try{
                FileWriter fw = new FileWriter(f+"\\logins.txt");
                System.out.println("file created");
            }
            catch(IOException ex1){
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    void addData(String usr, String pswd, String mail){
        RandomAccessFile raf;
        try {
            raf = new RandomAccessFile(f+"\\logins.txt", "rw");
            for(int i=0;i<ln;i++){
                raf.readLine();
            }
            raf.writeBytes("\r\n");
            raf.writeBytes("\r\n");
            raf.writeBytes("Username: "+usr +"\r\n");
            raf.writeBytes("Password: "+pswd +"\r\n");
            raf.writeBytes("Email: "+mail);
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(IOException ex){
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    void checkData(String usr, String pswd){
        RandomAccessFile raf;
        try{
            raf = new RandomAccessFile(f+"\\logins.txt", "rw");
            String line = raf.readLine();
            Username=line.substring(10);
            Password=raf.readLine().substring(10);
            Email=raf.readLine().substring(7);
            if(usr.equals(Username)&pswd.equals(Password)){
                JOptionPane.showMessageDialog(null,"Password Matched");
            }
            else{
                JOptionPane.showMessageDialog(null,"Wrong User / Password");
            }
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(IOException ex){
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void countLines(){
        try {
            ln=1;
            RandomAccessFile raf = new RandomAccessFile(f+"\\logins.txt", "rw");
            for(int i=0; raf.readLine()!=null;i++){
                ln++;
                }
                System.out.println("number of line :"+ln);
            }
        
        catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(IOException ex){
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void checkPswd(String pswd, String con_pswd){
        
        if(pswd.equals(con_pswd)){
                System.out.println("Password Matched");
            }
            else{
                System.out.println("Wrong Password");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sign_Up_Panel = new javax.swing.JPanel();
        name_txt = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        email_txt = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        new_password_txt = new javax.swing.JLabel();
        new_password_field = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        confirm_password_txt = new javax.swing.JLabel();
        confirm_password_field = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        sign_up = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sign_Up_Panel.setBackground(new java.awt.Color(32, 33, 50));

        name_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name_txt.setForeground(new java.awt.Color(204, 255, 255));
        name_txt.setText("NAME :");

        name_field.setBackground(new java.awt.Color(32, 33, 50));
        name_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name_field.setForeground(new java.awt.Color(255, 255, 255));
        name_field.setToolTipText("");
        name_field.setBorder(null);
        name_field.setCaretColor(new java.awt.Color(255, 255, 255));

        email_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        email_txt.setForeground(new java.awt.Color(204, 255, 255));
        email_txt.setText("EMAIL ADDRESS :");

        email_field.setBackground(new java.awt.Color(32, 33, 50));
        email_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        email_field.setForeground(new java.awt.Color(255, 255, 255));
        email_field.setBorder(null);
        email_field.setCaretColor(new java.awt.Color(255, 255, 255));
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        new_password_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        new_password_txt.setForeground(new java.awt.Color(204, 255, 255));
        new_password_txt.setText("NEW PASSWORD :");

        new_password_field.setBackground(new java.awt.Color(32, 33, 50));
        new_password_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        new_password_field.setForeground(new java.awt.Color(255, 255, 255));
        new_password_field.setBorder(null);

        confirm_password_txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirm_password_txt.setForeground(new java.awt.Color(204, 255, 255));
        confirm_password_txt.setText("CONFIRM PASSWORD");

        confirm_password_field.setBackground(new java.awt.Color(32, 33, 50));
        confirm_password_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirm_password_field.setForeground(new java.awt.Color(255, 255, 255));
        confirm_password_field.setBorder(null);

        sign_up.setBackground(new java.awt.Color(0, 102, 102));
        sign_up.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sign_up.setForeground(new java.awt.Color(204, 204, 255));
        sign_up.setText("SIGN UP");
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Freehand521 BT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("-- SIGN UP --");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Already have an account?");

        jButton1.setBackground(new java.awt.Color(32, 33, 50));
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Login now.");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sign_Up_PanelLayout = new javax.swing.GroupLayout(Sign_Up_Panel);
        Sign_Up_Panel.setLayout(Sign_Up_PanelLayout);
        Sign_Up_PanelLayout.setHorizontalGroup(
            Sign_Up_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sign_Up_PanelLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(Sign_Up_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sign_Up_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(Sign_Up_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(confirm_password_txt)
                        .addComponent(confirm_password_field)
                        .addComponent(jSeparator4)
                        .addComponent(new_password_txt)
                        .addComponent(email_txt)
                        .addComponent(email_field)
                        .addComponent(jSeparator2)
                        .addComponent(name_txt)
                        .addComponent(name_field)
                        .addComponent(jSeparator1)
                        .addComponent(new_password_field)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Sign_Up_PanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );
        Sign_Up_PanelLayout.setVerticalGroup(
            Sign_Up_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_Up_PanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(name_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(email_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(new_password_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(new_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirm_password_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirm_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sign_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Sign_Up_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
        );

        getContentPane().add(Sign_Up_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 530, 450));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akmal Nizam\\Desktop\\CSC232 Final Project\\Pic\\SignUp.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed
        createFolder();
        readFile();
        countLines();
        checkPswd(new_password_field.getText(),confirm_password_field.getText());
        addData(name_field.getText(),new_password_field.getText(),email_field.getText());
        JOptionPane.showMessageDialog(null,"Thank you for Sign up");

        Login log = new Login();
        log.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_upActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sign_Up_Panel;
    private javax.swing.JPasswordField confirm_password_field;
    private javax.swing.JLabel confirm_password_txt;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_txt;
    private javax.swing.JPasswordField new_password_field;
    private javax.swing.JLabel new_password_txt;
    private javax.swing.JButton sign_up;
    // End of variables declaration//GEN-END:variables
}
